
            create table if not exists datalake_umbrella.umbrella_pedido_de_venda_cabecalho (pedc_id_cia string
, pedc_id_pedido string
, pedc_id_cliente string
, pedc_id_tranred string
, pedc_id_transp string
, pedc_dt_emissao timestamp
, pedc_dt_chegada timestamp
, pedc_dt_reg timestamp
, pedc_id_unineg string
, pedc_ped_cliente string
, pedc_id_venrep string
, pedc_id_venrep2 string
, pedc_dt_entrega1 timestamp
, pedc_id_filial string
, pedc_dt_entrega2 timestamp
, pedc_in_preferencia int
, pedc_in_atendimento string
, pedc_id_tabdes string
, pedc_id_tabpre string
, pedc_dt_conversao timestamp
, pedc_id_conpag string
, pedc_dt_base timestamp
, pedc_parcela_ipi int
, pedc_prazo_medio int
, pedc_in_consumidor string
, pedc_taxa_financ double
, pedc_id_natope string
, pedc_seq int
, pedc_aliqicms double
, pedc_tp_aprocom string
, pedc_dt_aprocom timestamp
, pedc_usuario_com string
, pedc_obs_com string
, pedc_tp_aprocr string
, pedc_dt_aprocr timestamp
, pedc_usuario_cre string
, pedc_obs_cre string
, pedc_fob_cif string
, pedc_id_moeda string
, pedc_vl_pedido_cr double
, pedc_vl_pedido_us double
, pedc_obs_pedido string
, pedc_id_contrato string
, pedc_in_pedido string
, pedc_situacao string
, pedc_dt_sit timestamp
, pedc_in_liber_vl_min_dup string
, pedc_in_acresaut string
, pedc_dt_ultalt timestamp
, pedc_hh_ultalt string
, pedc_usuario string
, pedc_dt_aprocr_prev timestamp
, pedc_id_pedido_ref string
, pedc_dt_prev_entrega1 timestamp
, pedc_dt_prev_entrega2 timestamp
, pedc_base_desc_cr double
, pedc_nu_mix int
, pedc_obs_nota string
, pedc_perc_desconto_vp double
, pedc_perc_desconto_bf double
, pedc_tp_desconto_det string
, pedc_vl_frete_cliente double
, pedc_id_cliente_ent string
, pedc_id_natope_ent string
, pedc_seq_ent int
, pedc_obs_etiqueta string
, pedc_obs_fiscal string
, pedc_vl_frete_cia double
, pedc_id_canal string
, pedc_op_mkt string
, pedc_in_tracking string
, pedc_vl_desp_financ double
, pedc_id_tippre string
, pedc_num_cv int
, pedc_dt_cv timestamp
, pedc_dt_pag_cli timestamp
, pedc_id_transp_ori string
, pedc_vl_desp_aces double
, pedc_id_modelo string
, pedc_id_pedido_libera string
, pedc_dt_limite_exp timestamp
, pedc_in_vai_wms string
, pedc_in_foi_wms string
, pedc_dt_foi_wms timestamp
, pedc_ddd_agenda string
, pedc_fone_agenda string
, pedc_periodo_agenda string
, pedc_vl_frete_cliente_ori double
, pedc_vl_frete_cia_ori double
, pedc_obs_fiscal_corpo string
, pedc_id_contrato_b2b string
, pedc_id_origem string
, pedc_in_transp_atende string
, pedc_obs_transp_atende string
, pedc_ref_parceiro_b2b string
, pedc_pz_transit int
, pedc_pz_cd int
, pedc_ip_origem string
, pedc_in_aprovado string
, pedc_dt_aprovado timestamp
, pedc_in_vai_pagto string
, pedc_in_foi_pagto string
, pedc_dt_foi_pagto timestamp
, pedc_vl_pedido double
, pedc_id_estabelec_exp string
, pedc_id_pedido_grupo string
, pedc_nu_cupom int
, pedc_vl_frete_tabela double
, pedc_id_tipo_transporte string
, pedc_id_meio_pagto_princ string
, pedc_id_tp_entrega string
, pedc_in_vai_fraude string
, pedc_in_foi_fraude string
, pedc_dt_foi_fraude timestamp
, pedc_in_quebra string
, pedc_id_ponto_orig string
, pedc_in_envia_loja string
, pedc_dt_ult_envio timestamp
, pedc_id_clasf_cliente string
, pedc_utm_source string
, pedc_utm_medium string
, pedc_utm_campaign string
, pedc_dt_entrega_prom timestamp
, pedc_datahora_limite_aprov timestamp
, pedc_dt_min_exped timestamp
, pedc_id_periodo_agenda string
, pedc_id_campanha_b2b string
, pedc_ped_externo string
, pedc_resp_cupom string
, pedc_premio_escolhido string
, pedc_motorista_retira string
, pedc_rg_motorista_retira string
, pedc_transportadora_retira string
, pedc_placa_retira string
, pedc_datahora_retira timestamp
, pedc_id_campanha_cupom string
, pedc_ped_loja string
, pedc_id_nf_libera string
, pedc_id_filial_libera string
, pedc_id_nf_consolidada string
, pedc_id_filial_consolidada string
, pedc_id_lista string
, pedc_id_marca string
, pedc_id_canal_ext string
, pedc_in_pagto_ativo string
, pedc_id_regiao string
, pedc_id_mega_rota string
, pedc_obs_wms string
, pedc_id_estabelec2 string
, pedc_cod_loja_retira string
, pedc_tp_lista string
, pedc_b2b_invoice_type string
, pedc_b2b_operation string
, pedc_in_bloqueio_b2b string
, pedc_id_clube string
, pedc_nome_recebedor string
, key_pedido_de_venda_cabecalho string
, data_inclusao_c timestamp
, data_carga timestamp) partitioned by (data_inclusao_p string)
            stored as parquet;

            create table if not exists tmp.umbrella_pedido_de_venda_cabecalho (pedc_id_cia string
, pedc_id_pedido string
, pedc_id_cliente string
, pedc_id_tranred string
, pedc_id_transp string
, pedc_dt_emissao timestamp
, pedc_dt_chegada timestamp
, pedc_dt_reg timestamp
, pedc_id_unineg string
, pedc_ped_cliente string
, pedc_id_venrep string
, pedc_id_venrep2 string
, pedc_dt_entrega1 timestamp
, pedc_id_filial string
, pedc_dt_entrega2 timestamp
, pedc_in_preferencia int
, pedc_in_atendimento string
, pedc_id_tabdes string
, pedc_id_tabpre string
, pedc_dt_conversao timestamp
, pedc_id_conpag string
, pedc_dt_base timestamp
, pedc_parcela_ipi int
, pedc_prazo_medio int
, pedc_in_consumidor string
, pedc_taxa_financ double
, pedc_id_natope string
, pedc_seq int
, pedc_aliqicms double
, pedc_tp_aprocom string
, pedc_dt_aprocom timestamp
, pedc_usuario_com string
, pedc_obs_com string
, pedc_tp_aprocr string
, pedc_dt_aprocr timestamp
, pedc_usuario_cre string
, pedc_obs_cre string
, pedc_fob_cif string
, pedc_id_moeda string
, pedc_vl_pedido_cr double
, pedc_vl_pedido_us double
, pedc_obs_pedido string
, pedc_id_contrato string
, pedc_in_pedido string
, pedc_situacao string
, pedc_dt_sit timestamp
, pedc_in_liber_vl_min_dup string
, pedc_in_acresaut string
, pedc_dt_ultalt timestamp
, pedc_hh_ultalt string
, pedc_usuario string
, pedc_dt_aprocr_prev timestamp
, pedc_id_pedido_ref string
, pedc_dt_prev_entrega1 timestamp
, pedc_dt_prev_entrega2 timestamp
, pedc_base_desc_cr double
, pedc_nu_mix int
, pedc_obs_nota string
, pedc_perc_desconto_vp double
, pedc_perc_desconto_bf double
, pedc_tp_desconto_det string
, pedc_vl_frete_cliente double
, pedc_id_cliente_ent string
, pedc_id_natope_ent string
, pedc_seq_ent int
, pedc_obs_etiqueta string
, pedc_obs_fiscal string
, pedc_vl_frete_cia double
, pedc_id_canal string
, pedc_op_mkt string
, pedc_in_tracking string
, pedc_vl_desp_financ double
, pedc_id_tippre string
, pedc_num_cv int
, pedc_dt_cv timestamp
, pedc_dt_pag_cli timestamp
, pedc_id_transp_ori string
, pedc_vl_desp_aces double
, pedc_id_modelo string
, pedc_id_pedido_libera string
, pedc_dt_limite_exp timestamp
, pedc_in_vai_wms string
, pedc_in_foi_wms string
, pedc_dt_foi_wms timestamp
, pedc_ddd_agenda string
, pedc_fone_agenda string
, pedc_periodo_agenda string
, pedc_vl_frete_cliente_ori double
, pedc_vl_frete_cia_ori double
, pedc_obs_fiscal_corpo string
, pedc_id_contrato_b2b string
, pedc_id_origem string
, pedc_in_transp_atende string
, pedc_obs_transp_atende string
, pedc_ref_parceiro_b2b string
, pedc_pz_transit int
, pedc_pz_cd int
, pedc_ip_origem string
, pedc_in_aprovado string
, pedc_dt_aprovado timestamp
, pedc_in_vai_pagto string
, pedc_in_foi_pagto string
, pedc_dt_foi_pagto timestamp
, pedc_vl_pedido double
, pedc_id_estabelec_exp string
, pedc_id_pedido_grupo string
, pedc_nu_cupom int
, pedc_vl_frete_tabela double
, pedc_id_tipo_transporte string
, pedc_id_meio_pagto_princ string
, pedc_id_tp_entrega string
, pedc_in_vai_fraude string
, pedc_in_foi_fraude string
, pedc_dt_foi_fraude timestamp
, pedc_in_quebra string
, pedc_id_ponto_orig string
, pedc_in_envia_loja string
, pedc_dt_ult_envio timestamp
, pedc_id_clasf_cliente string
, pedc_utm_source string
, pedc_utm_medium string
, pedc_utm_campaign string
, pedc_dt_entrega_prom timestamp
, pedc_datahora_limite_aprov timestamp
, pedc_dt_min_exped timestamp
, pedc_id_periodo_agenda string
, pedc_id_campanha_b2b string
, pedc_ped_externo string
, pedc_resp_cupom string
, pedc_premio_escolhido string
, pedc_motorista_retira string
, pedc_rg_motorista_retira string
, pedc_transportadora_retira string
, pedc_placa_retira string
, pedc_datahora_retira timestamp
, pedc_id_campanha_cupom string
, pedc_ped_loja string
, pedc_id_nf_libera string
, pedc_id_filial_libera string
, pedc_id_nf_consolidada string
, pedc_id_filial_consolidada string
, pedc_id_lista string
, pedc_id_marca string
, pedc_id_canal_ext string
, pedc_in_pagto_ativo string
, pedc_id_regiao string
, pedc_id_mega_rota string
, pedc_obs_wms string
, pedc_id_estabelec2 string
, pedc_cod_loja_retira string
, pedc_tp_lista string
, pedc_b2b_invoice_type string
, pedc_b2b_operation string
, pedc_in_bloqueio_b2b string
, pedc_id_clube string
, pedc_nome_recebedor string
, key_pedido_de_venda_cabecalho string
, data_inclusao_c timestamp
, data_carga timestamp, data_inclusao_p string);
        