
            create table if not exists datalake_umbrella.umbrella_pedido_de_venda_detalhes (pedd_id_cia string
, pedd_id_pedido string
, pedd_id_item string
, pedd_in_praut string
, pedd_pr_tabela double
, pedd_pr_final double
, pedd_perc_desconto double
, pedd_id_unidade string
, pedd_qt_ped double
, pedd_qt_fat double
, pedd_qt_dev double
, pedd_qt_rom double
, pedd_qt_cancia double
, pedd_qt_cancliente double
, pedd_perc_comissao double
, pedd_perc_comissao2 double
, pedd_id_emb string
, pedd_tp_emb string
, pedd_num_unidades int
, pedd_situacao string
, pedd_dt_sit timestamp
, pedd_op_desconto double
, pedd_dt_entrega timestamp
, pedd_pr_calc_tab double
, pedd_pr_calc_ped double
, pedd_qt_saldo_cliente double
, pedd_qt_saldo_aberto double
, pedd_qt_lib double
, pedd_in_aprovado string
, pedd_vl_servico double
, pedd_descr_servico string
, pedd_vl_frete_cliente double
, pedd_vl_frete_cia double
, pedd_qt_garantia int
, pedd_vl_desc_cond_unit double
, pedd_vl_desc_inc_total double
, pedd_cod_tp_variavel int
, pedd_nu_variavel int
, pedd_pz_fornecedor int
, pedd_vl_despesa_aces double
, pedd_vl_despesa_fin double
, pedd_id_estabelec_est string
, pedd_dt_est_terc timestamp
, pedd_id_item_pai string
, pedd_vl_frete_cli_unit double
, pedd_vl_frete_cia_unit double
, pedd_vl_desc_inc_unit double
, pedd_vl_desp_aces_unit double
, pedd_vl_desp_fin_unit double
, pedd_usuario string
, pedd_datahora timestamp
, pedd_tp_combo string
, pedd_id_item_kit string
, pedd_tp_estoque string
, pedd_num_item int
, pedd_id_nf_consol string
, pedd_num_item_nf_consol int
, pedd_id_filial_consol string
, pedd_item_nome string
, pedd_id_customizacao string
, pedd_obs_item string
, pedd_num_item_gar int
, pedd_id_item_gar string
, pedd_ped_cliente_gar string
, pedd_ped_loja_gar string
, pedd_cod_parceiro string
, pedd_perc_icms double
, pedd_base_icms double
, pedd_vl_icms double
, pedd_base_icms_unit double
, pedd_vl_icms_unit double
, pedd_perc_icms_st double
, pedd_base_icms_st double
, pedd_vl_icms_st double
, pedd_base_icms_st_unit double
, pedd_vl_icms_st_unit double
, key_pedido_de_venda_detalhes string
, data_inclusao_c timestamp
, data_carga timestamp) partitioned by (data_inclusao_p string)
            stored as parquet;

            create table if not exists tmp.umbrella_pedido_de_venda_detalhes (pedd_id_cia string
, pedd_id_pedido string
, pedd_id_item string
, pedd_in_praut string
, pedd_pr_tabela double
, pedd_pr_final double
, pedd_perc_desconto double
, pedd_id_unidade string
, pedd_qt_ped double
, pedd_qt_fat double
, pedd_qt_dev double
, pedd_qt_rom double
, pedd_qt_cancia double
, pedd_qt_cancliente double
, pedd_perc_comissao double
, pedd_perc_comissao2 double
, pedd_id_emb string
, pedd_tp_emb string
, pedd_num_unidades int
, pedd_situacao string
, pedd_dt_sit timestamp
, pedd_op_desconto double
, pedd_dt_entrega timestamp
, pedd_pr_calc_tab double
, pedd_pr_calc_ped double
, pedd_qt_saldo_cliente double
, pedd_qt_saldo_aberto double
, pedd_qt_lib double
, pedd_in_aprovado string
, pedd_vl_servico double
, pedd_descr_servico string
, pedd_vl_frete_cliente double
, pedd_vl_frete_cia double
, pedd_qt_garantia int
, pedd_vl_desc_cond_unit double
, pedd_vl_desc_inc_total double
, pedd_cod_tp_variavel int
, pedd_nu_variavel int
, pedd_pz_fornecedor int
, pedd_vl_despesa_aces double
, pedd_vl_despesa_fin double
, pedd_id_estabelec_est string
, pedd_dt_est_terc timestamp
, pedd_id_item_pai string
, pedd_vl_frete_cli_unit double
, pedd_vl_frete_cia_unit double
, pedd_vl_desc_inc_unit double
, pedd_vl_desp_aces_unit double
, pedd_vl_desp_fin_unit double
, pedd_usuario string
, pedd_datahora timestamp
, pedd_tp_combo string
, pedd_id_item_kit string
, pedd_tp_estoque string
, pedd_num_item int
, pedd_id_nf_consol string
, pedd_num_item_nf_consol int
, pedd_id_filial_consol string
, pedd_item_nome string
, pedd_id_customizacao string
, pedd_obs_item string
, pedd_num_item_gar int
, pedd_id_item_gar string
, pedd_ped_cliente_gar string
, pedd_ped_loja_gar string
, pedd_cod_parceiro string
, pedd_perc_icms double
, pedd_base_icms double
, pedd_vl_icms double
, pedd_base_icms_unit double
, pedd_vl_icms_unit double
, pedd_perc_icms_st double
, pedd_base_icms_st double
, pedd_vl_icms_st double
, pedd_base_icms_st_unit double
, pedd_vl_icms_st_unit double
, key_pedido_de_venda_detalhes string
, data_inclusao_c timestamp
, data_carga timestamp, data_inclusao_p string);
        