
            create table if not exists datalake_umbrella.umbrella_item_geral (iteg_id string
, iteg_id_cia string
, iteg_id_terceiro string
, iteg_id_fornec string
, iteg_cod_terceiro string
, iteg_cod_fornec string
, iteg_nome string
, iteg_nome_alt string
, iteg_nome_estran string
, iteg_id_conite string
, iteg_id_nbm string
, iteg_seq_nbm int
, iteg_id_procedencia string
, iteg_id_unides string
, iteg_id_unidve string
, iteg_id_unidco string
, iteg_fator_ve double
, iteg_fator_co double
, iteg_peso_unitario double
, iteg_peso_bruto double
, iteg_ean int
, iteg_tp_lote_serie string
, iteg_pz_validade int
, iteg_pz_min_recebto int
, iteg_pz_min_exped int
, iteg_pz_alarme_valid int
, iteg_in_fabric_valid string
, iteg_tp_embalagem string
, iteg_qt_sku double
, iteg_tp_abc string
, iteg_id_rotativ string
, iteg_nu_caixas_base int
, iteg_nu_caixas_alt int
, iteg_altura double
, iteg_largura string
, iteg_comprimento double
, iteg_in_tombado string
, iteg_id_depto string
, iteg_id_setor string
, iteg_id_familia string
, iteg_id_sub string
, iteg_situacao string
, iteg_datahora timestamp
, iteg_usuario string
, iteg_nu_itens int
, iteg_in_fiscal string
, iteg_usuario_fiscal string
, iteg_datahora_fiscal timestamp
, iteg_obs_fiscal string
, iteg_observacao string
, iteg_id_item_geral string
, iteg_in_envia_loja string
, iteg_dt_ult_envio timestamp
, iteg_pz_meses_fabr int
, iteg_fabricante_cnpj string
, iteg_fabricante_nome string
, iteg_fabricante_modelo string
, iteg_dt_ultcompra timestamp
, iteg_us_ult_envio string
, iteg_usuario_inc string
, iteg_datahora_inc timestamp
, iteg_pit_id string
, iteg_dt_lancamento timestamp
, iteg_qt_grade double
, iteg_dt_fora_linha timestamp
, iteg_qt_prevenda double
, iteg_in_marca_propria string
, iteg_cod_fabr int
, iteg_qt_por_emb int
, iteg_id_tipo_transporte string
, iteg_in_montagem string
, iteg_in_medicao_cubometro string
, iteg_in_nu_serie string
, iteg_tp_serial string
, iteg_tam_serial int
, iteg_qt_empilha int
, iteg_ajuste_empilha double
, iteg_tp_item string
, iteg_id_tp_virtual string
, iteg_in_vendido_separado string
, iteg_parent_ext string
, iteg_in_fci string
, iteg_id_marca_propria string
, iteg_cod_embalagem string
, iteg_cor string
, iteg_tamanho string
, key_item_geral string
, data_inclusao_c timestamp
, data_carga timestamp) partitioned by (data_inclusao_p string)
            stored as parquet;

            create table if not exists tmp.umbrella_item_geral (iteg_id string
, iteg_id_cia string
, iteg_id_terceiro string
, iteg_id_fornec string
, iteg_cod_terceiro string
, iteg_cod_fornec string
, iteg_nome string
, iteg_nome_alt string
, iteg_nome_estran string
, iteg_id_conite string
, iteg_id_nbm string
, iteg_seq_nbm int
, iteg_id_procedencia string
, iteg_id_unides string
, iteg_id_unidve string
, iteg_id_unidco string
, iteg_fator_ve double
, iteg_fator_co double
, iteg_peso_unitario double
, iteg_peso_bruto double
, iteg_ean int
, iteg_tp_lote_serie string
, iteg_pz_validade int
, iteg_pz_min_recebto int
, iteg_pz_min_exped int
, iteg_pz_alarme_valid int
, iteg_in_fabric_valid string
, iteg_tp_embalagem string
, iteg_qt_sku double
, iteg_tp_abc string
, iteg_id_rotativ string
, iteg_nu_caixas_base int
, iteg_nu_caixas_alt int
, iteg_altura double
, iteg_largura string
, iteg_comprimento double
, iteg_in_tombado string
, iteg_id_depto string
, iteg_id_setor string
, iteg_id_familia string
, iteg_id_sub string
, iteg_situacao string
, iteg_datahora timestamp
, iteg_usuario string
, iteg_nu_itens int
, iteg_in_fiscal string
, iteg_usuario_fiscal string
, iteg_datahora_fiscal timestamp
, iteg_obs_fiscal string
, iteg_observacao string
, iteg_id_item_geral string
, iteg_in_envia_loja string
, iteg_dt_ult_envio timestamp
, iteg_pz_meses_fabr int
, iteg_fabricante_cnpj string
, iteg_fabricante_nome string
, iteg_fabricante_modelo string
, iteg_dt_ultcompra timestamp
, iteg_us_ult_envio string
, iteg_usuario_inc string
, iteg_datahora_inc timestamp
, iteg_pit_id string
, iteg_dt_lancamento timestamp
, iteg_qt_grade double
, iteg_dt_fora_linha timestamp
, iteg_qt_prevenda double
, iteg_in_marca_propria string
, iteg_cod_fabr int
, iteg_qt_por_emb int
, iteg_id_tipo_transporte string
, iteg_in_montagem string
, iteg_in_medicao_cubometro string
, iteg_in_nu_serie string
, iteg_tp_serial string
, iteg_tam_serial int
, iteg_qt_empilha int
, iteg_ajuste_empilha double
, iteg_tp_item string
, iteg_id_tp_virtual string
, iteg_in_vendido_separado string
, iteg_parent_ext string
, iteg_in_fci string
, iteg_id_marca_propria string
, iteg_cod_embalagem string
, iteg_cor string
, iteg_tamanho string
, key_item_geral string
, data_inclusao_c timestamp
, data_carga timestamp, data_inclusao_p string);
        