
            create table if not exists datalake_umbrella.umbrella_pedido_venda_entrega_pagto (pepa_id_cia string
, pepa_id_pedido string
, pepa_seq int
, pepa_id_meio_pagto string
, pepa_vl_meio double
, pepa_dt_entrada timestamp
, pepa_nu_cartao string
, pepa_sit_cod_seguranca string
, pepa_cod_seguranca string
, pepa_titular_cartao string
, pepa_id_bandeira_cartao string
, pepa_dt_vencto_cartao string
, pepa_nu_parcelas int
, pepa_logradouro string
, pepa_compl string
, pepa_bairro string
, pepa_cep string
, pepa_cidade string
, pepa_uf string
, pepa_pais string
, pepa_pe_juros double
, pepa_vl_juros double
, pepa_vl_adicional_bo double
, pepa_dt_vencto_bo timestamp
, pepa_usuario string
, pepa_datahora timestamp
, pepa_ped_cliente string
, pepa_vl_meio_orig double
, pepa_id_vale string
, pepa_tid_vbv string
, pepa_vl_est_dia double
, pepa_cpf_tit_cartao string
, pepa_id_banco string
, pepa_cartao_6digs string
, pepa_id_motivo_reprov string
, pepa_id_agencia string
, pepa_id_conta string
, pepa_vl_juros_adm double
, pepa_pz_vencto int
, pepa_id_bandeira_cliente string
, pepa_nu_cupom string
, pepa_id_cond_pagto string
, pepa_numero string
, pepa_id_vale_ext string
, key_pedido_venda_entrega_pagto string
, data_inclusao_c timestamp
, data_carga timestamp) partitioned by (data_inclusao_p string)
            stored as parquet;

            create table if not exists tmp.umbrella_pedido_venda_entrega_pagto (pepa_id_cia string
, pepa_id_pedido string
, pepa_seq int
, pepa_id_meio_pagto string
, pepa_vl_meio double
, pepa_dt_entrada timestamp
, pepa_nu_cartao string
, pepa_sit_cod_seguranca string
, pepa_cod_seguranca string
, pepa_titular_cartao string
, pepa_id_bandeira_cartao string
, pepa_dt_vencto_cartao string
, pepa_nu_parcelas int
, pepa_logradouro string
, pepa_compl string
, pepa_bairro string
, pepa_cep string
, pepa_cidade string
, pepa_uf string
, pepa_pais string
, pepa_pe_juros double
, pepa_vl_juros double
, pepa_vl_adicional_bo double
, pepa_dt_vencto_bo timestamp
, pepa_usuario string
, pepa_datahora timestamp
, pepa_ped_cliente string
, pepa_vl_meio_orig double
, pepa_id_vale string
, pepa_tid_vbv string
, pepa_vl_est_dia double
, pepa_cpf_tit_cartao string
, pepa_id_banco string
, pepa_cartao_6digs string
, pepa_id_motivo_reprov string
, pepa_id_agencia string
, pepa_id_conta string
, pepa_vl_juros_adm double
, pepa_pz_vencto int
, pepa_id_bandeira_cliente string
, pepa_nu_cupom string
, pepa_id_cond_pagto string
, pepa_numero string
, pepa_id_vale_ext string
, key_pedido_venda_entrega_pagto string
, data_inclusao_c timestamp
, data_carga timestamp, data_inclusao_p string);
        