
                create table if not exists datalake_umbrella.umbrella_recm_nr_cabecalho (noca_id_cia string
, noca_id_filial string
, noca_id_nr string
, noca_dt_emissao timestamp
, noca_tp_nota string
, noca_id_terceiro string
, noca_num_nota_ref int
, noca_serie_ref string
, noca_especie_ref string
, noca_dt_emissao_ref timestamp
, noca_dt_saida_ref timestamp
, noca_id_natope string
, noca_seq_natope int
, noca_consumo_sn string
, noca_id_nr_comp string
, noca_id_conpag string
, noca_id_moeda_tit string
, noca_id_transp string
, noca_vl_merc double
, noca_base_icms double
, noca_vl_icms double
, noca_vl_icms_sub double
, noca_vl_icms_dest double
, noca_base_ipi double
, noca_vl_ipi double
, noca_vl_ipi_dest double
, noca_vl_servico double
, noca_vl_despesa double
, noca_vl_desconto double
, noca_vl_iss double
, noca_vl_irrf double
, noca_doc_irrf int
, noca_perc_inss double
, noca_base_inss double
, noca_vl_inss double
, noca_doc_inss int
, noca_vl_frete double
, noca_vl_aces double
, noca_vl_total double
, noca_vl_merc_c double
, noca_base_icms_c double
, noca_vl_icms_c double
, noca_vl_icms_sub_c double
, noca_base_ipi_c double
, noca_vl_ipi_c double
, noca_vl_total_c double
, noca_vl_merc_o double
, noca_base_icms_o double
, noca_vl_icms_o double
, noca_vl_icms_sub_o double
, noca_base_ipi_o double
, noca_vl_ipi_o double
, noca_vl_total_o double
, noca_peso_bruto double
, noca_in_contabilizada string
, noca_id_tipcan string
, noca_id_preparacao string
, noca_id_unineg string
, noca_obs string
, noca_situacao string
, noca_dt_situacao timestamp
, noca_usuario string
, noca_datahora timestamp
, noca_id_caminhao string
, noca_nu_lote int
, noca_vl_despesa_o double
, noca_vl_frete_o double
, noca_vl_aces_o double
, noca_vl_desconto_o double
, noca_in_suframa string
, noca_id_terceiro_rem string
, noca_num_nota_rem int
, noca_serie_rem string
, noca_dt_emissao_rem timestamp
, noca_in_nominal_forcado string
, noca_id_nr_rem string
, noca_in_consig string
, noca_in_complemento string
, noca_in_pendente string
, noca_vl_pis double
, noca_id_tributo string
, noca_base_irrf double
, noca_nu_dependentes int
, noca_vl_cofins double
, noca_usuario_registro string
, noca_datahora_registro timestamp
, noca_usuario_conferencia string
, noca_datahora_conferencia timestamp
, noca_vl_csll double
, noca_vl_desconto_cond double
, noca_vl_desconto_inc double
, noca_base_contr double
, noca_tp_end string
, noca_seq_end int
, noca_perc_inss_enc double
, noca_vl_inss_enc double
, noca_vl_pis_cred double
, noca_vl_cofins_cred double
, noca_vl_icms_sub_dest double
, noca_base_ii double
, noca_vl_ii double
, noca_vl_desp_aduaneiro double
, noca_vl_adicional double
, noca_vl_pis_imp double
, noca_vl_cofins_imp double
, noca_vl_cif double
, noca_in_conf_fisica string
, noca_fiscal_doc_ext int
, noca_base_icms_nred_destin double
, noca_base_icms_destin double
, noca_vl_icms_destin double
, noca_vl_icms_part_dest double
, noca_vl_icms_part_rem double
, noca_vl_icms_fecp_destin double
, key_id_recm_nr_cabecalho string
, key_recm_nr_cabecalho string
, data_carga timestamp) stored as parquet;
                create table if not exists tmp.umbrella_recm_nr_cabecalho like datalake_umbrella.umbrella_recm_nr_cabecalho stored as textfile;
            