
            create table if not exists datalake_umbrella.umbrella_nota_fiscal_cabecalho (nfca_id_cia string
, nfca_id_filial string
, nfca_num_nota int
, nfca_serie string
, nfca_id_natope string
, nfca_seq_natope int
, nfca_id_tipope string
, nfca_dt_emissao timestamp
, nfca_hr_emissao string
, nfca_in_es string
, nfca_dt_es timestamp
, nfca_hr_es string
, nfca_in_consumo string
, nfca_id_cliente_fat string
, nfca_id_cliente_ent string
, nfca_id_depos string
, nfca_id_ped string
, nfca_id_venrep string
, nfca_id_venrep2 string
, nfca_id_unineg string
, nfca_id_conpag string
, nfca_id_tabpre string
, nfca_base_icms double
, nfca_vl_icms double
, nfca_base_icms_sub double
, nfca_vl_icms_sub double
, nfca_vl_icms_dest double
, nfca_base_icms_sub_nred double
, nfca_vl_icms_sub_nred double
, nfca_vl_icms_sub_dest double
, nfca_vl_icms_suf double
, nfca_base_ipi double
, nfca_vl_ipi double
, nfca_vl_ipi_dest double
, nfca_vl_mercadoria double
, nfca_vl_frete double
, nfca_vl_seguro double
, nfca_vl_despesa double
, nfca_vl_ii double
, nfca_vl_desconto double
, nfca_vl_total_nota double
, nfca_id_filial_destino string
, nfca_id_depos_destino string
, nfca_cif_fob string
, nfca_id_transp string
, nfca_id_transpred string
, nfca_dt_entrega timestamp
, nfca_id_veiculo string
, nfca_id_especie string
, nfca_ped_cliente string
, nfca_nu_volumes string
, nfca_qt_volumes double
, nfca_peso_bruto double
, nfca_peso_liquido double
, nfca_in_geracao string
, nfca_nu_vias int
, nfca_dt_situacao timestamp
, nfca_situacao string
, nfca_usuario string
, nfca_vl_servico double
, nfca_vl_irrf double
, nfca_vl_iss double
, nfca_in_contabilizada string
, nfca_nu_lote int
, nfca_vl_desp_financ double
, nfca_perc_tarifa double
, nfca_vl_tarifa double
, nfca_cfoc_nome string
, nfca_id_canal string
, nfca_vl_pis double
, nfca_vl_cofins double
, nfca_vl_csll double
, nfca_vl_desconto_cond double
, nfca_vl_desconto_inc double
, nfca_id_contrato_b2b string
, nfca_id_filial_saida string
, nfca_in_envio string
, nfca_dt_envio timestamp
, nfca_doc_envio int
, nfca_id_campanha_b2b string
, nfca_di string
, nfca_dt_registro_di timestamp
, nfca_local_desemb string
, nfca_id_estado_aduaneiro string
, nfca_dt_desemb_aduaneiro timestamp
, nfca_cod_exportador string
, nfca_cod_fabr_estr string
, nfca_base_ii double
, nfca_vl_desp_aduaneiro double
, nfca_vl_adicional double
, nfca_vl_pis_imp double
, nfca_vl_cofins_imp double
, nfca_vl_cif double
, nfca_tp_integra_nfe string
, nfca_tp_fatura string
, nfca_perc_icms_dest double
, nfca_id_nf string
, nfca_id_nf_dup string
, nfca_id_nf_saida string
, nfca_id_nf_fatura string
, nfca_id_nf_remessa string
, nfca_id_nf_complementada string
, nfca_id_marca string
, nfca_id_canal_ext string
, nfca_usuario_reg string
, nfca_datahora_reg timestamp
, nfca_id_motivo_canc string
, nfca_id_nr string
, nfca_id_filial_nr string
, nfca_base_icms_nred_destin double
, nfca_base_icms_destin double
, nfca_vl_icms_destin double
, nfca_vl_icms_part_dest double
, nfca_vl_icms_part_rem double
, nfca_vl_icms_fecp_destin double
, key_recm_nr_cabecalho string
, key_nota_fiscal_cabecalho string
, data_inclusao_c timestamp
, data_carga timestamp) partitioned by (data_inclusao_p string)
            stored as parquet;

            create table if not exists tmp.umbrella_nota_fiscal_cabecalho (nfca_id_cia string
, nfca_id_filial string
, nfca_num_nota int
, nfca_serie string
, nfca_id_natope string
, nfca_seq_natope int
, nfca_id_tipope string
, nfca_dt_emissao timestamp
, nfca_hr_emissao string
, nfca_in_es string
, nfca_dt_es timestamp
, nfca_hr_es string
, nfca_in_consumo string
, nfca_id_cliente_fat string
, nfca_id_cliente_ent string
, nfca_id_depos string
, nfca_id_ped string
, nfca_id_venrep string
, nfca_id_venrep2 string
, nfca_id_unineg string
, nfca_id_conpag string
, nfca_id_tabpre string
, nfca_base_icms double
, nfca_vl_icms double
, nfca_base_icms_sub double
, nfca_vl_icms_sub double
, nfca_vl_icms_dest double
, nfca_base_icms_sub_nred double
, nfca_vl_icms_sub_nred double
, nfca_vl_icms_sub_dest double
, nfca_vl_icms_suf double
, nfca_base_ipi double
, nfca_vl_ipi double
, nfca_vl_ipi_dest double
, nfca_vl_mercadoria double
, nfca_vl_frete double
, nfca_vl_seguro double
, nfca_vl_despesa double
, nfca_vl_ii double
, nfca_vl_desconto double
, nfca_vl_total_nota double
, nfca_id_filial_destino string
, nfca_id_depos_destino string
, nfca_cif_fob string
, nfca_id_transp string
, nfca_id_transpred string
, nfca_dt_entrega timestamp
, nfca_id_veiculo string
, nfca_id_especie string
, nfca_ped_cliente string
, nfca_nu_volumes string
, nfca_qt_volumes double
, nfca_peso_bruto double
, nfca_peso_liquido double
, nfca_in_geracao string
, nfca_nu_vias int
, nfca_dt_situacao timestamp
, nfca_situacao string
, nfca_usuario string
, nfca_vl_servico double
, nfca_vl_irrf double
, nfca_vl_iss double
, nfca_in_contabilizada string
, nfca_nu_lote int
, nfca_vl_desp_financ double
, nfca_perc_tarifa double
, nfca_vl_tarifa double
, nfca_cfoc_nome string
, nfca_id_canal string
, nfca_vl_pis double
, nfca_vl_cofins double
, nfca_vl_csll double
, nfca_vl_desconto_cond double
, nfca_vl_desconto_inc double
, nfca_id_contrato_b2b string
, nfca_id_filial_saida string
, nfca_in_envio string
, nfca_dt_envio timestamp
, nfca_doc_envio int
, nfca_id_campanha_b2b string
, nfca_di string
, nfca_dt_registro_di timestamp
, nfca_local_desemb string
, nfca_id_estado_aduaneiro string
, nfca_dt_desemb_aduaneiro timestamp
, nfca_cod_exportador string
, nfca_cod_fabr_estr string
, nfca_base_ii double
, nfca_vl_desp_aduaneiro double
, nfca_vl_adicional double
, nfca_vl_pis_imp double
, nfca_vl_cofins_imp double
, nfca_vl_cif double
, nfca_tp_integra_nfe string
, nfca_tp_fatura string
, nfca_perc_icms_dest double
, nfca_id_nf string
, nfca_id_nf_dup string
, nfca_id_nf_saida string
, nfca_id_nf_fatura string
, nfca_id_nf_remessa string
, nfca_id_nf_complementada string
, nfca_id_marca string
, nfca_id_canal_ext string
, nfca_usuario_reg string
, nfca_datahora_reg timestamp
, nfca_id_motivo_canc string
, nfca_id_nr string
, nfca_id_filial_nr string
, nfca_base_icms_nred_destin double
, nfca_base_icms_destin double
, nfca_vl_icms_destin double
, nfca_vl_icms_part_dest double
, nfca_vl_icms_part_rem double
, nfca_vl_icms_fecp_destin double
, key_recm_nr_cabecalho string
, key_nota_fiscal_cabecalho string
, data_inclusao_c timestamp
, data_carga timestamp, data_inclusao_p string);
        