
            create table if not exists datalake_umbrella.umbrella_instancia (inst_id_instancia string
, inst_id_filial string
, inst_id_cia string
, inst_ped_cliente string
, inst_dh_abertura timestamp
, inst_id_terceiro_fat string
, inst_id_terceiro_ent string
, inst_email string
, inst_in_nova_entrega string
, inst_in_credito string
, inst_in_vale string
, inst_in_cartao string
, inst_in_especie string
, inst_tp_retorno string
, inst_in_forcado string
, inst_obs string
, inst_id_unineg string
, inst_id_canal string
, inst_id_entrega_raiz string
, inst_id_motivo_fim string
, inst_id_canal_com string
, inst_id_categoria string
, inst_vl_merc double
, inst_vl_frete double
, inst_usuario string
, inst_dh_ultalt timestamp
, inst_situacao string
, inst_id_processo string
, inst_id_motivo string
, inst_in_cheque string
, inst_in_faturado string
, inst_id_transp string
, inst_id_contrato string
, inst_vl_desp_financ_orig double
, inst_vl_desp_aces_orig double
, inst_vl_desp_financ_novo double
, inst_vl_desp_aces_novo double
, inst_vl_total_orig double
, inst_vl_total_novo double
, inst_vl_desc_cond double
, inst_vl_desc_inc double
, inst_vl_merc_novo double
, inst_vl_frete_novo double
, inst_vl_desc_cond_novo double
, inst_vl_desc_inc_novo double
, inst_pz_coleta int
, inst_in_cupom string
, inst_id_nf_orig string
, inst_ped_loja string
, inst_id_rma string
, inst_in_debito string
, inst_dt_registro timestamp
, inst_usuario_registro string
, key_instancia string
, data_inclusao_c timestamp
, data_carga timestamp) partitioned by (data_inclusao_p string)
            stored as parquet;

            create table if not exists tmp.umbrella_instancia (inst_id_instancia string
, inst_id_filial string
, inst_id_cia string
, inst_ped_cliente string
, inst_dh_abertura timestamp
, inst_id_terceiro_fat string
, inst_id_terceiro_ent string
, inst_email string
, inst_in_nova_entrega string
, inst_in_credito string
, inst_in_vale string
, inst_in_cartao string
, inst_in_especie string
, inst_tp_retorno string
, inst_in_forcado string
, inst_obs string
, inst_id_unineg string
, inst_id_canal string
, inst_id_entrega_raiz string
, inst_id_motivo_fim string
, inst_id_canal_com string
, inst_id_categoria string
, inst_vl_merc double
, inst_vl_frete double
, inst_usuario string
, inst_dh_ultalt timestamp
, inst_situacao string
, inst_id_processo string
, inst_id_motivo string
, inst_in_cheque string
, inst_in_faturado string
, inst_id_transp string
, inst_id_contrato string
, inst_vl_desp_financ_orig double
, inst_vl_desp_aces_orig double
, inst_vl_desp_financ_novo double
, inst_vl_desp_aces_novo double
, inst_vl_total_orig double
, inst_vl_total_novo double
, inst_vl_desc_cond double
, inst_vl_desc_inc double
, inst_vl_merc_novo double
, inst_vl_frete_novo double
, inst_vl_desc_cond_novo double
, inst_vl_desc_inc_novo double
, inst_pz_coleta int
, inst_in_cupom string
, inst_id_nf_orig string
, inst_ped_loja string
, inst_id_rma string
, inst_in_debito string
, inst_dt_registro timestamp
, inst_usuario_registro string
, key_instancia string
, data_inclusao_c timestamp
, data_carga timestamp, data_inclusao_p string);
        