use dw_umbrella;

create table if not exists dw_umbrella.umbrella_nf(
      key_nf                         string
    , data_registro 				 timestamp
	, filial                      	 int   
	, nf                          	 bigint  
	, serie                       	 string
	, cfop_nf                     	 int   
	, cfop_seq_nf                 	 int   
	, cfop_descricao_nf           	 string
	, modulo_gerencial_nf         	 string
	, tipo_operacao               	 string
	, operacao                    	 string
	, data_emissao                	 timestamp        
	, entrada_saida               	 string
	, data_entrada_saida          	 timestamp        
	, sub_inventario              	 int   
	, ie_fat												 string
	, cnpj_cpf_cliente_fatura     	 bigint  
	, nome_cliente_fatura         	 string
	, uf_cliente_fatura           	 string
	, cnpj_cpf_cliente_entrega    	 bigint  
	, nome_cliente_entrega        	 string
	, uf_cliente_entrega          	 string
	, codigo_unidade_negocio      	 int   
	, unidade_negocio             	 string
	, codigo_canal_venda          	 string
	, canal_venda                 	 string
	, entrega                     	 string
	, codigo_marca                	 int   
	, marca                       	 string
	, contrato_b2b                	 string
	, situacao                    	 string
	, sku                         	 bigint  
	, descricao_sku               	 string
	, codigo_depto                	 int   
	, departamento                	 string
	, cfop_item_nf                	 int   
	, cfop_seq_item_nf            	 int   
	, cfop_descricao_item_nf      	 string
	, modulo_gerencial_item_nf    	 string
	, valor_total_nf								 double
	, qt_fat                      	 double
	, preco_unitario              	 double
	, perc_icms                   	 double
	, base_icms                   	 double
	, valor_icms                  	 double
	, perc_icms_st                	 double
	, base_icms_st                	 double
	, valor_icms_st               	 double
	, base_reduzida_icms_st       	 double
	, valor_icms_destino          	 double
	, valor_icms_st_destino       	 double
	, valor_icms_suframa          	 double
	, ncm                         	 double
	, ncm_seq                     	 int   
	, perc_ipi                    	 double
	, base_ipi                    	 double
	, valor_ipi                   	 double
	, valor_ipi_destino           	 double
	, valor_mercadoria            	 double
	, valor_frete                 	 double
	, valor_seguro                	 double
	, valor_despesa               	 double
	, valor_ii                    	 double
	, valor_desconto              	 double
	, valor_total_item            	 double
	, valor_comissao              	 double
	, valor_comissao2             	 double
	, valor_servico               	 double
	, valor_servico_total         	 double
	, valor_irrf                  	 double
	, valor_iss                   	 double
	, valor_desp_financeira       	 double
	, valor_tarifa                	 double
	, valor_pis                   	 double
	, base_icms_reduzida          	 double
	, valor_icms_merc             	 double
	, valor_icms_frete            	 double
	, valor_icms_outros           	 double
	, valor_cofins                	 double
	, valor_cofins_merc           	 double
	, valor_cofins_frete          	 double
	, valor_cofins_outros         	 double
	, valor_pis_merc              	 double
	, valor_pis_frete             	 double
	, valor_pis_outros            	 double
	, perc_pis                    	 double
	, perc_cofins                 	 double
	, perc_csll                   	 double
	, valor_csll                  	 double
	, valor_csll_merc             	 double
	, valor_csll_frete            	 double
	, valor_csll_outros           	 double
	, desconto_condicional        	 double
	, desconto_incondicional      	 double
	, base_ipi_destino            	 double
	, base_icms_destino           	 double
	, base_icms_st_destino        	 double
	, base_ii                     	 double
	, valor_despesa_aduaneiro     	 double
	, valor_adicional             	 double
	, valor_pis_importacao        	 double
	, valor_cofins_importacao     	 double
	, valor_cif                   	 double
	, perc_icms_destino           	 double
	, perc_irrf                   	 double
	, perc_iss                    	 double
	, perc_reducao_icms           	 double
	, perc_reducao_icms_st        	 double
	, perc_icms_fecp              	 double
	, perc_icms_destin            	 double
	, perc_icms_fecp_destin       	 double
	, perc_reducao_icms_destin    	 double
	, base_icms_reduzida_destin   	 double
	, base_icms_destin            	 double
	, valor_icms_destin           	 double
	, perc_icms_destin_part       	 double
	, valor_icms_part_dest        	 double
	, valor_icms_part_rem         	 double
	, pauta_ipi                   	 string
	, pauto_st                    	 string
	, valor_icms_fecp_destin      	 double
	, perc_icms_dest_interna      	 double
	, valor_icms_part_dest_merc   	 double
	, valor_icms_part_dest_frete  	 double
	, valor_icms_part_dest_outros 	 double
	, valor_icms_part_rem_merc    	 double
	, valor_icms_part_rem_frete   	 double
	, valor_icms_part_rem_outros  	 double
	, valor_icms_fecp_dest_merc   	 double
	, valor_icms_fecp_dest_frete  	 double
	, valor_icms_fecp_dest_outros 	 double	
	, data_carga 					 timestamp)
partitioned by (data_registro_p     string)
stored as parquet;
