use dw_umbrella;

set hive.exec.dynamic.partition.mode=nonstrict;

insert overwrite table dw_umbrella.umbrella_nr partition (data_registro_p) 
select key_nr						
     , data_registro 				
     , filial                        
     , nr                            
     , data_emissao                  
     , tipo_operacao                 
     , operacao     
     , ie_fornecedor                 
     , cnpj_cpf_fornecedor           
     , razao_social_nome_fornecedor  
     , nf_ref                        
     , serie_ref                     
     , data_emissao_ref              
     , cfop_nr                       
     , cfop_seq_nr                   
     , cfop_descricao_nr             
     , modulo_gerencial_nr           
     , codigo_cond_pagto             
     , condicao_pagamento            
     , situacao                      
     , sku                           
     , descricao_sku                 
     , ncm                           
     , ncm_seq                       
     , sub_inventario                
     , cod_depto                     
     , departamento                  
     , qt_uc                         
     , qt_ue   
     , valor_total_nf                      
     , preco_unitario                
     , perc_ipi                      
     , valor_merc                    
     , base_icms                     
     , perc_icms                     
     , valor_icms                    
     , valor_icms_st                 
     , valor_icms_destino            
     , valor_ipi                     
     , valor_ipi_destino             
     , valor_servico                 
     , valor_despesa                 
     , valor_frete                   
     , valor_desconto                
     , valor_aces                    
     , perc_iss                      
     , valor_iss                     
     , perc_irrf                     
     , valor_irrf                    
     , qt_uc_c                       
     , valor_merc_c                  
     , valor_icms_c                  
     , valor_icms_st_c               
     , valor_ipi_c                   
     , qt_uc_o                       
     , valor_merc_o                  
     , valor_icms_o                  
     , valor_icms_st_o               
     , valor_ipi_o                   
     , valor_despesa_o               
     , valor_frete_o                 
     , valor_aces_o                  
     , valor_desconto_o              
     , valor_pis                     
     , base_icms_reduzida            
     , valor_icms_merc               
     , valor_icms_frete              
     , valor_icms_outros             
     , valor_cofins                  
     , valor_cofins_merc             
     , valor_cofins_frete            
     , valor_cofins_outros           
     , valor_pis_merc                
     , valor_pis_frete               
     , valor_pis_outros              
     , perc_pis                      
     , perc_cofins                   
     , perc_csll                     
     , valor_cssl                    
     , valor_csll_merc               
     , valor_csll_frete              
     , valor_csll_outros             
     , valor_desconto_condicional    
     , valor_desconto_incondicional  
     , qt_dev_uc                     
     , qt_dev_ue                     
     , qt_dev_ue_fat                 
     , qt_devforn_ue                 
     , base_icms_c                   
     , base_icms_o                   
     , base_icms_reduzida_c          
     , base_icms_reduzida_o          
     , base_ipi                      
     , base_ipi_c                    
     , base_ipi_o                    
     , perc_reducao_icms             
     , valor_total                   
     , valor_total_c                 
     , valor_total_o                 
     , base_irrf                     
     , valor_inss                    
     , valor_inss_enc                
     , valor_pis_cred                
     , valor_cofins_cred             
     , valor_icms_st_destino         
     , base_icms_st_o                
     , base_icms_st                  
     , base_icms_st_c                
     , base_ii                       
     , valor_ii                      
     , valor_despesa_aduaneira       
     , valor_adicional               
     , valor_pis_imp                 
     , valor_cofins_imp              
     , valor_cif                     
     , valor_custo                   
     , perc_icms_st                  
     , valor_icms_st_ret             
     , base_icms_st_ret              
     , perc_icms_fecp                
     , perc_icms_destin              
     , perc_icms_fecp_destin         
     , perc_reducao_icms_destin      
     , base_icms_reduzida_destin     
     , base_icms_destin              
     , valor_icms_destin             
     , perc_icms_destino_part        
     , valor_icms_part_destino       
     , valor_icms_part_rem           
     , perc_margem_lucro             
     , perc_reducao_icms_st          
     , ipi_pauta                     
     , st_pauta                      
     , valor_icms_fecp_destin        
     , perc_icms_destino_interna     
     , valor_despesa_financeira_o    
     , perc_st_ret                   
     , perc_margem_lucro_ret         
     , valor_icms_st_ret_fornecedor  
     , base_icms_ret                 
     , valor_icms_ret                
     , perc_icms_ret                 
     , valor_icms_part_destino_merc  
     , valor_icms_part_destino_frete 
     , valor_icms_part_destino_outros
     , valor_icms_part_rem_merc      
     , valor_icms_part_rem_frete     
     , valor_icms_part_rem_outros    
     , valor_icms_fecp_destino_merc  
     , valor_icms_fecp_destino_frete 
     , valor_icms_fecp_destino_outros
     , data_carga 		
     , data_registro_p			
from datalake_umbrella.umbrella_nr;