use dw_umbrella;

set hive.exec.dynamic.partition.mode=nonstrict;

insert overwrite table dw_umbrella.umbrella_nf partition (data_registro_p) 
select key_nf        
     , data_registro					
	 , filial                      	
	 , nf                          	
	 , serie                       	
	 , cfop_nf                     	
	 , cfop_seq_nf                 	
	 , cfop_descricao_nf           	
	 , modulo_gerencial_nf         	
	 , tipo_operacao               	
	 , operacao                    	
	 , data_emissao                	
	 , entrada_saida               	
	 , data_entrada_saida          	
	 , sub_inventario  
	 , ie_fat            	
	 , cnpj_cpf_cliente_fatura     	
	 , nome_cliente_fatura         	
	 , uf_cliente_fatura           	
	 , cnpj_cpf_cliente_entrega    	
	 , nome_cliente_entrega        	
	 , uf_cliente_entrega          	
	 , codigo_unidade_negocio      	
	 , unidade_negocio             	
	 , codigo_canal_venda          	
	 , canal_venda                 	
	 , entrega                     	
	 , codigo_marca                	
	 , marca                       	
	 , contrato_b2b                	
	 , situacao                    	
	 , sku                         	
	 , descricao_sku               	
	 , codigo_depto                	
	 , departamento                	
	 , cfop_item_nf                	
	 , cfop_seq_item_nf            	
	 , cfop_descricao_item_nf      	
	 , modulo_gerencial_item_nf   
	 , valor_total_nf 	
	 , qt_fat                      	
	 , preco_unitario              	
	 , perc_icms                   	
	 , base_icms                   	
	 , valor_icms                  	
	 , perc_icms_st                	
	 , base_icms_st                	
	 , valor_icms_st               	
	 , base_reduzida_icms_st       	
	 , valor_icms_destino          	
	 , valor_icms_st_destino       	
	 , valor_icms_suframa          	
	 , ncm                         	
	 , ncm_seq                     	
	 , perc_ipi                    	
	 , base_ipi                    	
	 , valor_ipi                   	
	 , valor_ipi_destino           	
	 , valor_mercadoria            	
	 , valor_frete                 	
	 , valor_seguro                	
	 , valor_despesa               	
	 , valor_ii                    	
	 , valor_desconto              	
	 , valor_total_item            	
	 , valor_comissao              	
	 , valor_comissao2             	
	 , valor_servico               	
	 , valor_servico_total         	
	 , valor_irrf                  	
	 , valor_iss                   	
	 , valor_desp_financeira       	
	 , valor_tarifa                	
	 , valor_pis                   	
	 , base_icms_reduzida          	
	 , valor_icms_merc             	
	 , valor_icms_frete            	
	 , valor_icms_outros           	
	 , valor_cofins                	
	 , valor_cofins_merc           	
	 , valor_cofins_frete          	
	 , valor_cofins_outros         	
	 , valor_pis_merc              	
	 , valor_pis_frete             	
	 , valor_pis_outros            	
	 , perc_pis                    	
	 , perc_cofins                 	
	 , perc_csll                   	
	 , valor_csll                  	
	 , valor_csll_merc             	
	 , valor_csll_frete            	
	 , valor_csll_outros           	
	 , desconto_condicional        	
	 , desconto_incondicional      	
	 , base_ipi_destino            	
	 , base_icms_destino           	
	 , base_icms_st_destino        	
	 , base_ii                     	
	 , valor_despesa_aduaneiro     	
	 , valor_adicional             	
	 , valor_pis_importacao        	
	 , valor_cofins_importacao     	
	 , valor_cif                   	
	 , perc_icms_destino           	
	 , perc_irrf                   	
	 , perc_iss                    	
	 , perc_reducao_icms           	
	 , perc_reducao_icms_st        	
	 , perc_icms_fecp              	
	 , perc_icms_destin            	
	 , perc_icms_fecp_destin       	
	 , perc_reducao_icms_destin    	
	 , base_icms_reduzida_destin   	
	 , base_icms_destin            	
	 , valor_icms_destin           	
	 , perc_icms_destin_part       	
	 , valor_icms_part_dest        	
	 , valor_icms_part_rem         	
	 , pauta_ipi                   	
	 , pauto_st                    	
	 , valor_icms_fecp_destin      	
	 , perc_icms_dest_interna      	
	 , valor_icms_part_dest_merc   	
	 , valor_icms_part_dest_frete  	
	 , valor_icms_part_dest_outros 	
	 , valor_icms_part_rem_merc    	
	 , valor_icms_part_rem_frete   	
	 , valor_icms_part_rem_outros  	
	 , valor_icms_fecp_dest_merc   	
	 , valor_icms_fecp_dest_frete  	
	 , valor_icms_fecp_dest_outros 	
	 , data_carga 					
	 , data_registro_p	 		 	
from datalake_umbrella.umbrella_nf;